from django.db import models
from unicodedata import category
from django.utils import timezone
from django.contrib.auth.models import User
 
class Bible(models.Model):
    session_tag = models.CharField(blank=False,max_length=9999)
    ui_order = models.IntegerField()
    html_code = models.TextField()
    navbar_code = models.TextField(null=True, blank=True)

class friends(models.Model):
    ad_user = models.CharField(max_length=999, primary_key=True)
    url = models.CharField(max_length=999, null=True, blank=True, default='')
    token = models.CharField(max_length=999, null=True, blank=True, default='')
    field1 = models.CharField(max_length=999, null=True, blank=True, default='')
    field2 = models.CharField(max_length=999, null=True, blank=True, default='')
    field3 = models.CharField(max_length=999, null=True, blank=True, default='')
    field4 = models.CharField(max_length=999, null=True, blank=True, default='')
    field5 = models.CharField(max_length=999, null=True, blank=True, default='')
    field6 = models.CharField(max_length=999, null=True, blank=True, default='')
    field7 = models.CharField(max_length=999, null=True, blank=True, default='')
    field8 = models.CharField(max_length=999, null=True, blank=True, default='')
    field9 = models.CharField(max_length=999, null=True, blank=True, default='')
    field10 = models.CharField(max_length=999, null=True, blank=True, default='')
    field11 = models.CharField(max_length=999, null=True, blank=True, default='')
    field12 = models.CharField(max_length=999, null=True, blank=True, default='')
    field13 = models.CharField(max_length=999, null=True, blank=True, default='')
    field14 = models.CharField(max_length=999, null=True, blank=True, default='')
    field15 = models.CharField(max_length=999, null=True, blank=True, default='')
    field16 = models.CharField(max_length=999, null=True, blank=True, default='')
    field17 = models.CharField(max_length=999, null=True, blank=True, default='')
    field18 = models.CharField(max_length=999, null=True, blank=True, default='')

class check(models.Model):
    ad_user = models.CharField(max_length=999, primary_key=True)
    token = models.CharField(max_length=999, null=True, blank=True, default='')
    field1 = models.CharField(max_length=999, null=True, blank=True, default='')
    field2 = models.CharField(max_length=999, null=True, blank=True, default='')
    field3 = models.CharField(max_length=999, null=True, blank=True, default='')
    field4 = models.CharField(max_length=999, null=True, blank=True, default='')
    field5 = models.CharField(max_length=999, null=True, blank=True, default='')
    field6 = models.CharField(max_length=999, null=True, blank=True, default='')
    field7 = models.CharField(max_length=999, null=True, blank=True, default='')
    field8 = models.CharField(max_length=999, null=True, blank=True, default='')
    field9 = models.CharField(max_length=999, null=True, blank=True, default='')
    field10 = models.CharField(max_length=999, null=True, blank=True, default='')
    field11 = models.CharField(max_length=999, null=True, blank=True, default='')
    field12 = models.CharField(max_length=999, null=True, blank=True, default='')
    field13 = models.CharField(max_length=999, null=True, blank=True, default='')
    field14 = models.CharField(max_length=999, null=True, blank=True, default='')
    field15 = models.CharField(max_length=999, null=True, blank=True, default='')
    field16 = models.CharField(max_length=999, null=True, blank=True, default='')
    field17 = models.CharField(max_length=999, null=True, blank=True, default='')
    field18 = models.CharField(max_length=999, null=True, blank=True, default='')
    field19 = models.CharField(max_length=999, null=True, blank=True, default='')
    field20 = models.CharField(max_length=999, null=True, blank=True, default='')
    field21 = models.CharField(max_length=999, null=True, blank=True, default='')
    field22 = models.CharField(max_length=999, null=True, blank=True, default='')