# Generated by Django 4.2.5 on 2023-10-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bible',
            old_name='welcome',
            new_name='html_code',
        ),
    ]
