# Generated by Django 4.2.5 on 2023-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0002_rename_welcome_bible_html_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bible',
            name='session_tag',
            field=models.CharField(default='welcome', max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bible',
            name='ui_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
