# Generated by Django 4.2.5 on 2023-10-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0003_bible_session_tag_bible_ui_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bible',
            name='navbar_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
