# Generated by Django 4.2.5 on 2023-12-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newbie", "0004_bible_navbar_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="bible",
            name="form_code",
            field=models.TextField(default="好"),
            preserve_default=False,
        ),
    ]
