# Generated by Django 4.2.5 on 2023-12-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0005_bible_form_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
