# Generated by Django 4.2.5 on 2023-12-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0006_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='names',
        ),
    ]
