# Generated by Django 4.2.5 on 2023-12-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0009_remove_friends_id_remove_friends_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bible',
            name='form_code',
        ),
    ]
