# Generated by Django 4.2.5 on 2023-12-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0010_remove_bible_form_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='url',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
