# Generated by Django 4.2.5 on 2023-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0011_friends_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('ad_user', models.CharField(max_length=999, primary_key=True, serialize=False)),
                ('field1', models.CharField(blank=True, max_length=999, null=True)),
                ('field2', models.CharField(blank=True, max_length=999, null=True)),
                ('field3', models.CharField(blank=True, max_length=999, null=True)),
                ('field4', models.CharField(blank=True, max_length=999, null=True)),
                ('field5', models.CharField(blank=True, max_length=999, null=True)),
                ('field6', models.CharField(blank=True, max_length=999, null=True)),
                ('field7', models.CharField(blank=True, max_length=999, null=True)),
                ('field8', models.CharField(blank=True, max_length=999, null=True)),
                ('field9', models.CharField(blank=True, max_length=999, null=True)),
                ('field10', models.CharField(blank=True, max_length=999, null=True)),
                ('field11', models.CharField(blank=True, max_length=999, null=True)),
                ('field12', models.CharField(blank=True, max_length=999, null=True)),
                ('field13', models.CharField(blank=True, max_length=999, null=True)),
                ('field14', models.CharField(blank=True, max_length=999, null=True)),
                ('field15', models.CharField(blank=True, max_length=999, null=True)),
                ('field16', models.CharField(blank=True, max_length=999, null=True)),
                ('field17', models.CharField(blank=True, max_length=999, null=True)),
                ('field18', models.CharField(blank=True, max_length=999, null=True)),
                ('field19', models.CharField(blank=True, max_length=999, null=True)),
                ('field20', models.CharField(blank=True, max_length=999, null=True)),
                ('field21', models.CharField(blank=True, max_length=999, null=True)),
                ('field22', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
    ]
