# Generated by Django 4.2.5 on 2023-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0012_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='field1',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field10',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field11',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field12',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field13',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field14',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field15',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field16',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field17',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field18',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field19',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field2',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field20',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field21',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field22',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field3',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field4',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field5',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field6',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field7',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field8',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='field9',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field1',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field10',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field11',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field12',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field13',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field14',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field15',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field16',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field17',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field18',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field2',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field3',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field4',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field5',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field6',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field7',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field8',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='field9',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='url',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
    ]
