# Generated by Django 4.2.5 on 2024-01-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0013_alter_check_field1_alter_check_field10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='token',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
    ]
