# Generated by Django 4.2.5 on 2024-01-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0014_friends_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='token',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
    ]
